# The root directory where all the
# runtime data goes in.
root = "kubernix"

[log]
dir = "log"
level = "info"

[pki]
dir = "pki"

[kube]
dir = "kube"
cluster-cidr = "10.200.0.0/16"
service-cidr = "10.50.0.0/24"
cluster-dns = "10.50.0.10"

[crio]
dir = "crio"
cidr = "10.100.0.0/16"
