root = "run"

[log]
dir = "log"
level = "debug"

[pki]
dir = "pki"

[kube]
dir = "kube"
cluster-cidr = "172.200.0.0/16"
service-cidr = "172.50.0.0/24"
cluster-dns = "172.50.0.10"

[crio]
dir = "crio"
cidr = "172.100.0.0/16"
