---
version: 2.1

executors:
  container:
    docker:
      - image: nixos/nix

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - lint-clippy
      - lint-rustfmt

prepare-env: &prepare-env
  run:
    name: Install dependencies
    command: |
      apk add bash ca-certificates curl findutils git make openssh
      eval 'ssh-agent -s'
      env

jobs:
  build:
    executor: container
    steps:
      - <<: *prepare-env
      - checkout
      - restore_cache:
          keys:
            - v1-build-{{ checksum "nix/nixpkgs.json" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: build
          command: make
      - save_cache:
          key: v1-build-{{ checksum "nix/nixpkgs.json" }}-{{ checksum "Cargo.lock" }}
          paths:
            - /nix
            - target
            - ~/.cargo

  lint-clippy:
    executor: container
    steps:
      - <<: *prepare-env
      - checkout
      - restore_cache:
          keys:
            - v1-lint-clippy-{{ checksum "nix/nixpkgs.json" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: clippy
          command: make lint-clippy
      - save_cache:
          key: v1-lint-clippy-{{ checksum "nix/nixpkgs.json" }}-{{ checksum "Cargo.lock" }}
          paths:
            - /nix
            - target
            - ~/.cargo

  lint-rustfmt:
    executor: container
    steps:
      - <<: *prepare-env
      - checkout
      - restore_cache:
          keys:
            - v1-lint-rustfmt-{{ checksum "nix/nixpkgs.json" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: rustfmt
          command: make lint-rustfmt
      - save_cache:
          key: v1-lint-rustfmt-{{ checksum "nix/nixpkgs.json" }}-{{ checksum "Cargo.lock" }}
          paths:
            - /nix
            - target
            - ~/.cargo
